Repository amuratech/digiflash, pull requests merged in 2020-04, with the labels that each got.

#10 State, base filters added to prs
  public/index.html
  src/api/git.js
  src/components/App.js
  src/components/Banner.js
  src/components/Dashboard.js
  src/components/Footer.js
  src/components/Header.js
  src/components/PrList.js
  src/components/SearchBar.js
  src/components/UserData.js
  src/components/UserInfo.js
  src/index.js
Labels: changes_done, enhancement

#17 [issue-11] Add banner on home page
  package.json
  src/components/App.js
  src/components/Header.js
  src/components/PrList.js
  src/components/PrTabs.js
  src/index.js
Labels: waiting_for_merge_review

#16 Add pagination component
  src/api/git.js
  src/components/Pagination.js
  src/components/PrList.js
Labels: enhancement, needs_explanation

#21 [Bug-18]: Fix pagination error
  src/components/Pagination.js
  src/components/PrList.js
Labels: bug, changes_done

#20 [ISSUE-11] Add banner
  src/components/App.js
  src/components/Banner.css
  src/components/Banner.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.js
  src/components/PrList.js
  src/components/PrTabs.css
  src/components/PrTabs.js
Labels: changes_done

#24 [ISSUE-23] Bug - Footer Misplacement Issue
  src/components/App.css
  src/components/App.js
  src/components/Footer.css
  src/components/Footer.js
Labels: waiting_for_merge_review
